@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Client as client
entity Authenticator as auth
database Database as db

client -> auth : Send username and password
activate auth

auth -> db : Check username and password
activate db

alt valid login
    db --> auth: Valid username and password
    deactivate db

    auth -> auth : Generate session id
    auth -> db : Save session id for username
    activate db
    db --> auth : Session id saved
    deactivate db

    auth --> client : Save session id as cookie
    auth --> client : Redirect to user page
    deactivate auth

else invalid login
    autonumber 3
    db --> auth: Invalid username or password
    deactivate db

    auth --> client : Display invalid login message
    deactivate auth

end

@enduml